### PR TITLE
Add support for Python 3.12.

### PR DESCRIPTION
**Pull request by icemac**
Add preliminary support for Python 3.13a2.

### CODE REVIEW

**Comment by icemac** [comment]
And I thought that the windows permission problem was solved long time ago, bit it seems to reoccur in 3.12+: https://github.com/zopefoundation/DateTime/actions/runs/6846867512/job/18614143209?pr=57

**Review by dataflake — APPROVED** [review]

**Comment by icemac** [comment]
Yes there was https://github.com/zopefoundation/meta/pull/157 to fix this issue for DateTime, let my try to revert it to see if this helps for Python 3.12+.

**Comment by icemac** [comment]
@dataflake Do you think reverting meta/config#157 + changing `buildout.cfg` for windows is the correct path forward?

**Review by dataflake — APPROVED** [review]

**Comment by dataflake** [comment]
If it works it works. I honestly don't care about anything else.

**Pull request merged**
