### PR TITLE
Spelling and grammar fixes

### PR DESCRIPTION
**Pull request by scop**

### CODE REVIEW

**Comment by dataflake** [comment]
Would you please sign a contributor agreement so we can accept your contribution? Please see https://www.zope.dev/developer/becoming-a-committer.html for details.

**Comment by icemac** [comment]
Alternatively there is a documentation for a one time contribution: https://github.com/zopefoundation/meta/wiki/One-time-contribution

**Comment by dataflake** [comment]
@icemac This is the first time I am seeing instructions for a one-time contribution. I believe that process is insufficient and even dangerous, it taints the zopefoundation codebase with contributions where the Plone Foundation has no ownership. The contributor agreement assigns a lot more rights to the Plone Foundation than just "I am OK with this code being published under the ZPL". I think going with this one-time procedure is wrong and opens up a huge legal can of worms for the Plone Foundation. I am 100% against that procedure and will not allow any contributions made with it. Matter of fact, I'd really like you to delete that page and never mention that again, that's how bad I think it is.

**Comment by dataflake** [comment]
I don't want to take any legal risk so I have gone over the documentation and the docstrings myself. The result is at https://github.com/zopefoundation/DateTime/commit/1442a44b09166b8fb33913b2feefdfcf6b5fa1d6 and it supercedes this PR.

**Pull request closed without merging**
