### PR TITLE
Support unpickling instances having a numeric timezone like +0430.

### PR DESCRIPTION
**Pull request by fdiary**
To fix error in unpickling DateTime object having '+NNNN' timezone #3.

### CODE REVIEW

**Comment by tseaver** [comment]
Thanks for the patch!  Can you please add unit tests for the cases you outlined in #3?

**Comment by fdiary** [comment]
Thanks for your reply ! I added a test and re-pushed the branch.

**Comment by tseaver** [comment]
@fdiary thanks for the update!  I will merge as soon as Travis passes.

**Comment by fdiary** [comment]
@tseaver thanks for merging. I'm looking forward the new release !

**Pull request merged**
