### PR TITLE
fix #39

### LINKED ISSUE #39: DateTime 4.5 unit test incompatible with Windows
In the process of updating the DateTime version pin for Zope and running the CI tests I discovered that a recent change is incompatible with Windows. The tests fail with this traceback:

```python
Error in test test_format (DateTime.tests.test_datetime.DateTimeTests)
Traceback (most recent call last):
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "c:\hostedtoolcache\windows\python\3.6.8\x64\lib\unittest\case.py", line 605, in run
    testMethod()
  File "d:\a\zope\zope\.tox\py36\eggs\datetime-4.5-py3.6.egg\DateTime\tests\test_datetime.py", line 690, in test_format
    result = dt.strftime(fmt)
  File "d:\a\zope\zope\.tox\py36\eggs\datetime-4.5-py3.6.egg\DateTime\DateTime.py", line 1566, in strftime
    microseconds).strftime(format)
ValueError: Invalid format string
```

The corresponding code is part of #37.

### PR DESCRIPTION
**Pull request by d-maurer**
Fixes #39
by avoiding the `-` format modifier (not suppoted by all C libraries)-

### CODE REVIEW

**Comment by d-maurer** [comment]
The Windows tests fail -- but already during the test run setup:
```
py310 run-test-pre: commands[0] | 'D:\a\DateTime\DateTime\.tox\py310\Scripts/buildout' -nc 'D:\a\DateTime\DateTime/buildout.cfg' 'buildout:directory=D:\a\DateTime\DateTime\.tox\py310' 'buildout:develop=D:\a\DateTime\DateTime' install test
Requires-Python support missing. 

Traceback (most recent call last):
  File "D:\a\DateTime\DateTime\.tox\py310\lib\site-packages\zc\buildout\patches.py", line 52, in patch_PackageIndex
    from pip._internal.index.collector import HTMLPage
ImportError: cannot import name 'HTMLPage' from 'pip._internal.index.collector' 
```

**Comment by dataflake** [comment]
The pip issue is not what causes the failure. I "forced" a fix for the pip issue by downgrading to a version < 22 and the test failure still shows. I don't know why there is no informative text output, though.

**Comment by d-maurer** [comment]
Jens Vagelpohl wrote at 2022-9-9 03:08 -0700:
>The pip issue is not what causes the failure. I "forced" a fix for the pip issue by downgrading to a version < 22 and the test failure still shows. I don't know why there is no informative text output, though.

The `py310` test run fails with exit exit code `2`. This may indicate
a "special" test run failure.

**Comment by d-maurer** [comment]
Dieter Maurer wrote at 2022-9-9 12:17 +0200:
>Jens Vagelpohl wrote at 2022-9-9 03:08 -0700:
>>The pip issue is not what causes the failure. I "forced" a fix for the pip issue by downgrading to a version < 22 and the test failure still shows. I don't know why there is no informative text output, though.
>
>The `py310` test run fails with exit exit code `2`. This may indicate
>a "special" test run failure.

`zope.testrunner` will not use exit code `2` (at least
not to indicate a failed test):
its `run` function has body
```
    failed = run_internal(defaults, args, script_parts=script_parts, cwd=cwd,
                          warnings=warnings)
    sys.exit(int(failed))
```
where *failed* has a boolean value.

This suggests: the exit code comes from something prior to
the activation of `zope.testrunner`.

**Comment by dataflake** [comment]
I think I see the problem. zc.buildout is creating the test script at `bin\test` but then tox wants to run it from `Scripts\test`. I'm trying to fix that now.

**Review by dataflake — APPROVED** [review]

**Pull request merged**
