### PR TITLE
add ci and conda publish actions 

### PR DESCRIPTION
**Pull request by fcakyon**
**adds continious integration ([on macos/linux/windows with python 3.5-8](https://github.com/fcakyon/DateTime/actions/runs/84835656)) and conda publish workflows using github actions**

adds features:
- automatically performs style check and unittests at every push/merge to master branch ([[tested on my fork]](https://github.com/fcakyon/DateTime/actions/runs/84835656))
- automatically publishes anaconda cloud package when new release is published on github ([[tested on my fork]](https://github.com/fcakyon/DateTime/runs/608928151?check_suite_focus=true), [[check anaconda cloud url]](https://anaconda.org/fcakyon/datetime/files))

requirements:
- get an Anaconda token (with read and write API access) at anaconda.org/USERNAME/settings/access and add it to the Secrets of the Github repository as ANACONDA_TOKEN

### CODE REVIEW

**Comment by dataflake** [comment]
I am strictly against adding yet another third party CI workflow unless this is discussed at the zopefoundation organization level and found to be OK for the whole zopefoundation organization.

**Comment by fcakyon** [comment]
> I am strictly against adding yet another third party CI workflow unless this is discussed at the zopefoundation organization level and found to be OK for the whole zopefoundation organization.

What do you mean by "3rd party ci workflow"? It is based on [official github actions](https://github.com/features/actions).

**Comment by jamadden** [comment]
I concur with @dataflake.

**Comment by dataflake** [comment]
> > I am strictly against adding yet another third party CI workflow unless this is discussed at the zopefoundation organization level and found to be OK for the whole zopefoundation organization.
> 
> What do you mean by "3rd party ci workflow"? It is based on [official github actions](https://github.com/features/actions).


This "conda"/"anaconda" thing is a third party that we are not using on any other repository in the entire zopefoundation GitHub organization.

I'm sure you put a lot of effort into this, but changing infrastructure like CI workflows is out of the question without top-level decisions and plans/volunteers to roll that out across all repositories.

I will also note that signing the contributor agreement is a basic prerequisite for anything, and it appears you haven't done so?

**Comment by fcakyon** [comment]
> > > I am strictly against adding yet another third party CI workflow unless this is discussed at the zopefoundation organization level and found to be OK for the whole zopefoundation organization.
> > 
> > 
> > What do you mean by "3rd party ci workflow"? It is based on [official github actions](https://github.com/features/actions).
> 
> This "conda"/"anaconda" thing is a third party that we are not using on any other repository in the entire zopefoundation GitHub organization.
> 
> I'm sure you put a lot of effort into this, but changing infrastructure like CI workflows is out of the question without top-level decisions and plans/volunteers to roll that out across all repositories.
> 
> I will also note that signing the contributor agreement is a basic prerequisite for anything, and it appears you haven't done so?

[Anaconda cloud](https://anaconda.org/) is a distribution framework similar to [PYPI](https://pypi.org/). 

We want to publish [pycaret](https://github.com/pycaret/pycaret) (which requires your library) to anaconda cloud, however all dependencies should have a conda distribution build to do so. All required packages except "DateTime" and "datefinder" is present as a package in anaconda cloud. With this pull request, I am trying to add support for automatic conda publishing support to this repo.

How can I sign this contributor agreement?

**Comment by dataflake** [comment]
Information about becoming a contributor is at https://www.zope.org/developer/becoming-a-committer.html

I'm still unclear why you can't just download an egg file and upload it to wherever you need it if PyPI for some odd reason is not working. Why would the project need to support publishing to some place that is not the official Python package repository? Isn't this something you can do yourself?

**Comment by fcakyon** [comment]
Yes I have already published this project [as a conda package](https://anaconda.org/fcakyon/datetime/files). Thought that you would want to add official conda support. If you don't want it, it is OK.

**Comment by dataflake** [comment]
Let's just say that in the 20+ year history of this code (and any other Zope package that I am involved in) there hasn't been any request to publish packages in other places than PyPI. If there was high demand from various parties, maybe. But until then I suggest you publish what you need by hand.

**Pull request closed without merging**
